# ====== macOS Configuration ======
# The following configuration is only for macOS

game_window:
  size: [686, 1280]
  title_bar_height: 90         # ğŸ“ Title Bar Height (Note titel bar will be cropped before window resize)

monster_detect:
  hp_bar_color: [90, 201, 108] # (B,G,R)

minimap:
  player_color: [84, 255, 255] # BGR
  other_player_color: [20, 15, 228] # BGR
  debug_window_upscale: 2

party_red_bar:
  lower_red: [4, 80, 50] # â¤ï¸ HSV, darker red of party health bar
  upper_red: [5, 90, 90] # â¤ï¸ HSV, brighter red of party health bar

rune_solver:
  arrow_highlight_low_hsv: [340, 50, 85]    # ğŸ”´
  arrow_highlight_high_hsv: [110, 100, 100] # ğŸ”´
